services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8080"
    depends_on:
      - orders
      - payments
    networks:
      - orbita-net

  orders:
    build: ./orders-service
    container_name: orders-service
    ports:
      - "${ORDERS_SERVICE_PORT}:8081"
    environment:
      SPRING_DATASOURCE_URL: ${ORDERS_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    depends_on:
      postgres-orders:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - orbita-net

  payments:
    build: ./payments-service
    container_name: payments-service
    ports:
      - "${PAYMENTS_SERVICE_PORT}:8082"
    environment:
      SPRING_DATASOURCE_URL: ${PAYMENTS_SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    depends_on:
      postgres-payments:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - orbita-net

  postgres-orders:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_ORDERS_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_ORDERS_HOST_PORT}:5432"
    volumes:
      - postgres_orders_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_ORDERS_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - orbita-net

  postgres-payments:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_PAYMENTS_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PAYMENTS_HOST_PORT}:5432"
    volumes:
      - postgres_payments_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_PAYMENTS_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - orbita-net

  kafka:
    image: apache/kafka:3.9.2
    container_name: kafka
    hostname: kafka
    ports:
      - "${KAFKA_HOST_PORT}:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - orbita-net

networks:
  orbita-net:
    driver: bridge

volumes:
  postgres_payments_data:
  postgres_orders_data:
